clear, clc

files = {'controllability_example.m', ...
         'elastic_roa_example.m', ...
         'feedback_linearization_example.m', ...
         'linear_response_example.m', ...
         'linearization_equilibrium_example.m', ...
         'linearization_example.m', ...
         'mass_spring_response_example.m', ...
         'nonlinear_response_example.m', ...
         'symtf2symss_example.m'};
     
d = pwd;
hd = [d, '/html'];

for k = 1:numel(files)
    
end
% builddocsearchdb(hd);
