%% Mass-Spring Demo
clear, clc, close all, reset(symengine)

syms m l g k y T
syms theta(t)

f1 = m*(l^2)*diff(theta, 2) == m*g*l*sin(theta) - k*diff(theta) + T;
g1 = y == theta;

savedemo('mass_spring', ...
    'Variables', {m, l, g, k}, ...
    'StateEquations', {f1}, ...
    'OutputEquations', {g1}, ...
    'States', {theta, diff(theta)}, ...
    'Inputs', {T}, ...
    'Outputs', {y});
